# Generated by Django 2.1.5 on 2019-10-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restuarant',
            new_name='Restaurant',
        ),
    ]
